### ISSUE TITLE
Howdy!  Is there a list of changes from version Winstats.70 to your new Winstats.80 ?

### ISSUE THREAD

**Issue by bobolobo** [mixmastamyk/winstats#1]

**Comment by mixmastamyk** [comment]
Hi, no there are no changes in the code, only metadata.  

I moved the repo over here because bitbucket is deleting all mercurial repos soon.

I needed to update the links on its page on PyPi, so needed to make a new release.  It is a mature project so I bumped it a larger bump than I normally would have.  Perhaps should have used 1.0... not sure.  

Long term, I'm not planning on making any major changes as I rarely use Windows any more.

**Comment by bobolobo** [comment]
Sorry for repetitive question. 

Anyway only one real question.  I am using this list comprehension to get eight stats:

      line_of_data = [winstats.get_perf_data(i, fmts='double') for i in stats_list]


If one of the processes I am monitoring is down I get this generic error:

      "PdhCollectQueryData failed: PDH_NO_DATA"

Is there a way to get the actual name of the statistic to be printed out?  I guess I could use a regular for loop and cycle through each statistic that way and use the index variable name to give me the statistic that is down.  But list comprehensions are so efficient, clean, and cool :)

**Comment by mixmastamyk** [comment]
Yes, I think a for loop is the only way to do that currently.

I believe in Python 2 the loop variable would leak into the enclosing scope, so you could use (in your example) the variable i after the list comprehension.  But they "fixed" that so it is no longer available.

A for loop is probably easier to read than a comprehension with error checking inside.
